batch_size: 32
num_epochs: 10
lr: 3e-4
weight_decay: 0.0

d_model: 256
nhead: 1  # ğŸš« å•å¤´æ³¨æ„åŠ›
num_encoder_layers: 3
num_decoder_layers: 3
dim_feedforward: 512

data_dir: "data"
save_dir: "results"
model_path: "best_model.pt"
